### ISSUE TITLE
Validation of custom entered values

### ISSUE THREAD

**Issue by dnyg** [configit/ngyn#106]
I'm using ngyn-select2 in an input field to select between a list of email adresses.

Users can, however, add a new one, which is implemented using createSearchChoice.

Where/how should I add my validation logic for this input? Is there an event when a new searchChoice is created I can bind to?

**Comment by chad-configit** [comment]
Hi Dnyg,

My first comment would be that I personally haven't used createSearchChoice - the application I work on doesn't require it - so I haven't any meaningful experience of this feature.

`ngyn-select2` is a simple wrapper over select2 and I normally advise that things are done "the select2 way". In this case I believe that means implementing your validation logic inside the createSearchChoice function, returning `null` if validation fails.

With that said, I would like to further understand what the validation logic is that you're referring to. Could you give some example code covering this scenario?

**Comment by Dnyg** [comment]
In `select2` you can solve the problem by using the createTag function, but that doesn't work using `ngyn-select2`

Select2 describes it here: https://select2.org/tagging#constraining-tag-creation

```
createTag: function(input) {
  //Implement validation logic here. Return null if invalid.
}
```

**Comment by chad-configit** [comment]
What version of select2 are you using. As far as I can tell createTag was created in 4.0.x and ngyn-select2 has never been developed to work against that version. In my quick test it fails to initialize properly
