### ISSUE TITLE
do we have loading remote data for ngyn-select2

### ISSUE THREAD

**Issue by dsaikumar** [configit/ngyn#76]
Do we have angular integration for the component like this image
![screen shot 2015-11-24 at 3 05 42 pm](https://cloud.githubusercontent.com/assets/2561955/11362942/dc95b858-92bc-11e5-8811-dc0f1c5507e8.png)

So I can load my data asynchronously on user input

**Comment by chad-configit** [comment]
Hi @dsaikumar, sorry for the late reply. the `ngyn-select2` directive takes an object which are the options to initialize select2 with. These options allow you to specify the ajax behavior.

Anything you can do with a normal select2, you should be able to achieve via ngyn-select2.

e.g.

```html
<input type='hidden' id="ajaxSelect" name="Video"
       ngyn-select2="videoSelectOptions"
       data-placeholder="Select a video"
       ng-model="vm.video"
       required>
</input>
```

Note that the control has to be an `input` to allow dynamic population

```javascript
$scope.videoSelectOptions = {
  minimumInputLength: 2,
  query: function( options ) {
    VideoService.query( {
      $search: options.term,
      $top: 20,
      $skip: ( options.page - 1 ) * 20,
      $orderby: 'Title ASC'
    }, function( data ) {
      var more = options.page * 20 < data.totalCount;
      options.callback( { results: data, more: more } );
    } );
  },
  formatResult: function( item ) {
    return item.name;
  },
  formatSelection: function( item ) {
    return item.name;
  }
};
```

HTH

**Comment by dsaikumar** [comment]
Thanks @chad-configit, it worked.
But by default I am not able to display some default values before user starts search.

**Comment by chad-configit** [comment]
> Can we display some default values before user starts search.

I'm not too sure what you mean by this, but I expect if select2 is capable of doing it, it can be done via this directive. If there's something about the directive blocking it, please let me know.

**Comment by dsaikumar** [comment]
The loading of remote data worked using the select2#3.4.5 version for me.

**Comment by dsaikumar** [comment]
I have one issue with this way of loading the values for the dropdown using remotely.
## Using the ngyn directive as to load data using ajax call


Prequisties :

> jquery : https://github.com/jquery/jquery-dist#1.9.1

> select2 : https://github.com/ivaynberg/select2#3.4.5

> ngyn-select2 : ngyn-select2.js(I have this in my project from longback, I can't replace it, so I figured out the following usage)


####Usage of the directive

HTML Code

    <input type='hidden' id="ajaxSelect" name="Search"
       ngyn-select2="searchOptions"
       data-placeholder="Select a video"
       ng-model="data.modelObject" multiple
       required style="width: 500px"></input>


Controller Code

    'use strict';
    angular.module('appName').controller('ResearchController',
     function($scope,$http){
      $scope.data={modelObject:[]};
      $scope.searchOptions = {
        minimumInputLength: 2,
        query: function( options ) {
         $http.get(url)
         .then(function(response){
           var requiredData=[];
           //Morph the data from the response and set in requiredData
           options.callback( {
             results: requiredData,
             more: false
           });
        });
      },
      formatResult: function( item ) {
        return item.name;//Return the key to display in dropdown
      },
      formatSelection: function( item ) {
        return item.name; //Return the key to display after selection is done in input box
      }
     };
    });

**Comment by maxoizs** [comment]
@dsaikumar you missing the binding key ex: `key="id"` as mentioned in the [docs](http://configit.github.io/ngyn/)

**Comment by chad-configit** [comment]
> you missing the binding key ex: key="id"

That only applies to the `select` element

**Comment by shranand** [comment]
@chad-configit is an initSelection possible while using the ngyn-select2 directive this way? This is to show a default value pre-selected.
